### ISSUE TITLE
Feature Request: Enhancing the UI. 

### ISSUE THREAD

**Issue by Ardent10** [moja-global/community-website#310] opened 2022-03-08 16:52 UTC
### Is your feature request related to a problem? Please describe.

1) Currently there is no segregation between two blogs. There is no color difference to make user understand a new blog has started.
2) 2022 and 2021 LFX Mentees are combined together and the "How to get involved" section and the Tags are repeated.
3) The left side bar (Recent post) also looks odd  as it does not differentiate between the blog and itself due to its current background color.
4) The Theme toggle button has a moon and a bulb.
![image](https://user-images.githubusercontent.com/73132031/157282775-647ab1ac-7aea-4fcb-8405-4d1f53b2b2c1.png)

### Describe the solution you'd like.

1) For the blog section we can have a better background color for segregation between blogs.
2) To  show mentees of different year we can create a Link on the left bar as 2021 Mentees, 2022 Mentees and so on, and now in this case we don't have to repeat the "How to get involved" section and tags. We can write it only once and then it will show on each year blog page. 
3) Left bar should also have a different background color. Some styling will do.
somewhat like this.
![image](https://user-images.githubusercontent.com/73132031/157286143-902ee961-4c28-435d-a17c-b38bbab2f0d3.png)

4) Moon -Sun combination will be much better and Moon-bulb is not that great of a combination. 

### Describe alternatives you've considered

For the blog section we can Add a slider instead of creating a long page of the selected mentees.

**Comment by ShadyResurrected** [comment] 2022-03-08 16:55
Hi, I am Chandradeep Chandra, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you

**Comment by harshi606** [comment] 2022-03-08 17:13
Hello , my name is Harshithaa.This is something I'd like to work on. As soon as I have resolved the problem, I will raise a PR once the issue is solved. Thank you very much

**Comment by Deeks900** [comment] 2022-03-09 07:18
Hey! I'm Deeksha, a contributor to OpenForce 2022. I would like to work on these two issues: 
Currently, there is no segregation between the two blogs. There is no color difference to make users understand a new blog has started.
The Theme toggle button has a moon and a bulb.
Could you please assign these two issues to me?

**Comment by Ardent10** [comment] 2022-03-09 12:27
Relax guys 😅,I am not the project admin. I am also a participant in Openforce22 and I raised this issue to work on it as well.

**Comment by Aaditya-Singh78** [comment] 2022-03-10 09:01
Hi, I am Aaditya Singh, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you

**Comment by PrabhuRaamDev** [comment] 2022-03-15 04:15
Hi, I am Prabhu raam, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue.

**Closed** 2022-04-15 09:30 UTC
Labels: enhancement, needs-triage, Issue:No-Activity
